test:vega20:
  extends: .test
  dependencies:
    - build:rocm
  tags:
    - vega20
    - rocm

# Allow Fiji to fail
test:s9300:
  extends: .test
  variables:
    ROCM_REPO_URL: "http://repo.radeon.com/rocm/apt/.apt_2.3/"
  dependencies:
    - build:rocm_beta
  tags:
    - s9300
    - rocm
  allow_failure: true

test:mi25:
  extends: .test
  dependencies:
    - build:rocm
  tags:
    - mi25
    - rocm
